### PR TITLE
Search order improvement

### LINKED ISSUE #464: Query improvement
The goal is to improve the query usage through the web interface. Modifiers such as 'limit' are better handled separately. This is important to enable per page query, for example to combine an author filter along with the global filter. In that situation it's tricky to support modifier in both filters.

- [x] Remove order by and limit from the query language.
- [x] Update the web search bar to include order-by and limit input.
- [x] Add field alias from and to for 'created_at<' and 'created_at>'.
- [x] Add project field.
- [x] Add search alias configuration: [(Name, Expr)].

```yaml
  search_aliases:
    - name: "approved"
      alias: "(approval:Code-Review+2)"
    - name: "sprint-01"
      alias: "from:2021-01-03 to:201-01-24"
```

### PR DESCRIPTION
**Pull request by TristanCacqueray**
Fixes #464

### CODE REVIEW

**Review by morucci — CHANGES_REQUESTED** [review]
It seems difficult to include the display of the order setting in the board column edition. Why not just displaying it in the column or table (like it is done in the table view for the search string) ?
However, not sure if that will fit in the column view but a suggestion would be to display a tooltip when the cursor is on the column/table title to display the search string + the selected order. wdyt ?

**Comment by TristanCacqueray** [comment]
Yes it is tricky to display in the editor. We can move the controller in the view below, or we could also add a line return in the editor? I was thinking the limit could also be set per column, so we need more room.

**Comment by morucci** [comment]
> Yes it is tricky to display in the editor. We can move the controller in the view below

Yes it's worth a try.

Also we can probably limit the amount of keys a user can sort on.

**Comment by TristanCacqueray** [comment]
We currently only support a single search order key.

@morucci could you please take a look at the latest commit?

**Comment by morucci** [comment]
yes that's better. Could we remove from the order keys the one that are not displayed in the table ? It does not make sense to order on repo_regex or project for instance.

**Comment by TristanCacqueray** [comment]
Ok for the regex, but why not enabling sorting per project? We could add a `sortable` attribute to the field, but in the meantime 913ff78 simply remove regex field from the controller.

**Review by morucci — APPROVED** [review]

**Pull request merged**
