### PR TITLE
crawler - Github PR - relax ratelimit in case deactivated in GHE

### PR DESCRIPTION
**Pull request by morucci**
According to #958, the rate limit system can be deactivated in GHE.

This change updates the Github PR crawler to handle a ratelimit returned as null by the API. In this case Macroscope's GraphQL stream handler does not check for the internal RateLimit object because stored as Nothing then the waiting delay to honor a ratelimit is skipped.

Related to issue: #958

This commit does not handle the case for other Github crawlers. If this is accepted some follow-up patches will be needed to handle this is other Github crawlers.

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
That looks good to me, and it would be great to see if that fixes the issue. Otherwise we could also wait for the new error handling suggested in the drainEntities comment?

**Comment by jumanjiman** [comment]
> it would be great to see if that fixes the issue

i'm attempting to build and test locally against our private GHE instance.

I'm reverse-engineering the build steps from `.github/workflow/publish-*` to build an image locally for test.

**Comment by jumanjiman** [comment]
I definitely got further, and
this PR  appears to solve the ratelimit issue.

I assume that I built it correctly off the PR code because 
my local Docker build successfully retrieves the first page of 100 org repos (out of > 200).

```
❯ COMPOSE_MONOCLE_VERSION='latest' docker-compose up -d; docker-compose logs -f
  CTRL-C

❯ docker-compose logs crawler
Attaching to monocle_crawler_1
crawler_1  | 2022-09-29 15:02:34 INFO    Macroscope.Main:86: Starting monitoring service {"port":9001}
crawler_1  | 2022-09-29 15:02:34 INFO    Macroscope.Main:113: Starting to fetch streams
crawler_1  | 2022-09-29 15:02:34 INFO    Macroscope.Main:165: Starting crawlers {"crawlers":["https://ghe.example.com/api/graphql-c62b49fd70efd25dfbbf08a573369660f85164ca for GHE"]}
crawler_1  | 2022-09-29 15:02:34 INFO    Macroscope.Main:179: Group starting {"group":"https://ghe.example.com/api/graphql-c62b49fd70efd25dfbbf08a573369660f85164ca for GHE"}
crawler_1  | 2022-09-29 15:02:34 INFO    Macroscope.Main:304: Starting crawler {"index":"monocle-test","crawler":"GHE"}
crawler_1  | 2022-09-29 15:02:34 INFO    Macroscope.Worker:144: Looking for oldest entity {"index":"monocle-test","crawler":"GHE","stream":"Projects","offset":0}
crawler_1  | 2022-09-29 15:02:34 INFO    Macroscope.Worker:156: Processing {"index":"monocle-test","crawler":"GHE","stream":"Projects","entity":{"contents":"internalorg","tag":"Organization"},"age":"2021-01-01T00:00:00Z"}
crawler_1  | 2022-09-29 15:02:36 INFO    Lentille.GraphQL:210: Fetched from current page {"index":"monocle-test","crawler":"GHE","stream":"Projects","count":0,"total":0,"pageInfo":{"endCursor":null,"hasNextPage":false,"totalCount":null},"ratelimit":null}
crawler_1  | 2022-09-29 15:02:36 WARNING Macroscope.Worker:180: Error occured when consuming the document stream
    {"index":"monocle-test","crawler":"GHE","stream":"Projects","err":"DecodeError
        [\"Unknown GetProjects response: GetProjects
        {rateLimit = Nothing, organization = Just (OrganizationOrganization
            {repositories = OrganizationRepositoriesRepositoryConnection
                {totalCount = 227, pageInfo = OrganizationRepositoriesPageInfoPageInfo
                    {hasNextPage = True, endCursor = Just \\\"Y3Vyc29yOnYyOpHNFpg=\\\"}, nodes = Just [Just (OrganizationRepositoriesNodesRepository
                        {nameWithOwner = \\\"internalorg/transition\\\"}),Just (OrganizationRepositoriesNodesRepository
                        -- redact ~12 repos --
                        {nameWithOwner = \\\"internalorg/IMPORTANT_REPO\\\"}),Just (OrganizationRepositoriesNodesRepository
                        -- redact ~84 repos --
                        {nameWithOwner = \\\"internalorg/quickscan\\\"})
        ]}})}\"]"}
crawler_1  | 2022-09-29 15:02:36 INFO    Macroscope.Worker:144: Looking for oldest entity {"index":"monocle-test","crawler":"GHE","stream":"Projects","offset":1}
crawler_1  | 2022-09-29 15:02:36 INFO    Macroscope.Worker:149: Unable to find entity to update {"index":"monocle-test","crawler":"GHE","stream":"Projects"}
crawler_1  | 2022-09-29 15:02:36 INFO    Macroscope.Worker:144: Looking for oldest entity {"index":"monocle-test","crawler":"GHE","stream":"TaskDatas","offset":0}
crawler_1  | 2022-09-29 15:02:36 INFO    Macroscope.Worker:156: Processing {"index":"monocle-test","crawler":"GHE","stream":"TaskDatas","entity":{"contents":"internalorg/IMPORTANT_REPO","tag":"TaskDataEntity"},"age":"2021-01-01T00:00:00Z"}
crawler_1  | 2022-09-29 15:02:38 WARNING Macroscope.Main:300: Skipping due to an unexpected exception {"index":"monocle-test","crawler":"GHE","err":"Invalid response: GetLinkedIssues {rateLimit = Nothing, search = SearchSearchResultItemConnection {issueCount = 0, pageInfo = SearchPageInfoPageInfo {hasNextPage = False, endCursor = Nothing}, nodes = Just []}}\nCallStack (from HasCallStack):\n  error, called at src/Relude/Debug.hs:289:11 in relude-1.1.0.0-5JycKJkJeebDcuDsd66BY7:Relude.Debug\n  error, called at src/Lentille/GitHub/Issues.hs:116:18 in monocle-0.1.7.0-5C5VzWDrxK4JM5qtcn0kfv:Lentille.GitHub.Issues"}
crawler_1  | 2022-09-29 15:02:38 INFO    Macroscope.Main:182: Group end {"group":"https://ghe.example.com/api/graphql-c62b49fd70efd25dfbbf08a573369660f85164ca for GHE"}
```

**Comment by TristanCacqueray** [comment]
@jumanjiman 3d70054 should fix the decode error, please let us know if that works for you and we'll merge this PR.

**Comment by jumanjiman** [comment]
building locally now...

**Comment by jumanjiman** [comment]
> should fix the decode error, please let us know if that works for you and we'll merge this PR.

@TristanCacqueray Thank you for your patience.
The crawser is crawling away and delivering lots of great info into other components.

Looks great!

**Comment by morucci** [comment]
@TristanCacqueray let's approved to make it land please :)

**Review by TristanCacqueray — APPROVED** [review]

**Comment by jumanjiman** [comment]
@TristanCacqueray @morucci 

This project is so freaking cool! ❤️

**Comment by TristanCacqueray** [comment]
@jumanjiman thank you for taking the time to report the issue in detail, such feedback is greatly appreciated!

**Pull request merged**
