### PR TITLE
Update start.sh to prevent failure when title contains a space

### PR DESCRIPTION
**Pull request by morucci**

### CODE REVIEW

**Comment by morucci** [comment]
@georgettica could you check ? This fixes my test deployment with a TITLE set to "Monocle Devel"

**Comment by georgettica** [comment]
Yeah, I will check

**Comment by TristanCacqueray** [comment]
Well, with #715 , the monocle api now implements an about endpoint we could use to provide those variables, so I think we should be able to drop the start.sh soon.

**Comment by georgettica** [comment]
actually, I am now getting a network error (maybe because I am exposing traffic for the `web` component and the API is not accessible on port 8080 🤷

**Comment by georgettica** [comment]
I'll try that later tomorrow :)

**Comment by morucci** [comment]
> Well, with #715 , the monocle api now implements an about endpoint we could use to provide those variables, so I think we should be able to drop the start.sh soon.



> Well, with #715 , the monocle api now implements an about endpoint we could use to provide those variables, so I think we should be able to drop the start.sh soon.

Probably for the title var, yes. Perhaps not for the api url. Would you like to create an issue for this ?

**Comment by morucci** [comment]
I'll merge this as it fix an issue.

**Comment by morucci** [comment]
@TristanCacqueray could you place you approval plz?

**Review by TristanCacqueray — APPROVED** [review]

**Pull request merged**
